apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elastic-operator
  namespace: elastic
spec:
  interval: 24h
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: '2.12.0'
      sourceRef:
        kind: HelmRepository
        name: elastic-operator
        namespace: elastic
      interval: 1m