apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: strimzi
  namespace: kafka
spec:
  interval: 24h
  url: https://strimzi.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi/strimzi-kafka-operator
      version: '0.42.0'
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
      interval: 1m
  # values:
  #   harborAdminPassword: "admin"
  #   expose:
  #     type: ingress
  #     tls:
  #       enabled: true
  #       certSource: auto
  #     ingress:
  #       hosts:
  #         core: harbor.gangstack.com
  #       annotations:
  #         kubernetes.io/ingress.class: nginx
  #         cert-manager.io/cluster-issuer: "letsencrypt"
  #       tls:
  #         - hosts:
  #             - harbor.gangstack.com
  #   externalURL: https://harbor.gangstack.com