---
apiVersion: v1
kind: Namespace
metadata:
  name: lkextra
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: lkextra-operator
  namespace: lkextra
spec:
  interval: 24h
  url: https://github.com/gangyi89/lkextra-operator/chart