apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  interval: 2m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt
        hosts: 
          - "grafana.gangstack.com"
        tls:
          - secretName: grafana-general-tls
            hosts:
              - "grafana.gangstack.com"

        path: /
    alertmanager:
      enabled: true
    prometheus:
      enabled: true